const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.Dictionary,
		C3.Plugins.HTMLElement,
		C3.Plugins.Particles,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Particles.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.ChangeTags,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.JavaScriptInEvents.GebeurtenissenBlad1_Event18_Act1,
		C3.Plugins.Touch.Cnds.OnHoldGesture,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetScale
	];
};
self.C3_JsPropNameTable = [
	{Price: 0},
	{Background: 0},
	{Layer: 0},
	{image: 0},
	{Audio: 0},
	{NewProject: 0},
	{Afbeelding: 0},
	{Muis: 0},
	{Aanraking: 0},
	{Money: 0},
	{Tekst: 0},
	{NewProject2: 0},
	{Tekst2: 0},
	{SpeedPrice: 0},
	{MoneyPrice: 0},
	{c2bcb432b9924503971fd73b5f32c313removebgpreview: 0},
	{AutoPrice: 0},
	{a0c1171745b8b57199db5fcea2f5removebgpreview: 0},
	{LocalStorage: 0},
	{Dictionary: 0},
	{b599bd04938a2da758362c0ef74removebgpreview: 0},
	{HTMLElement2: 0},
	{Afbeelding2: 0},
	{cursorpointersymbolpng: 0},
	{Click2Start: 0},
	{Text: 0},
	{Particles2: 0},
	{dollarsignpngtransparent: 0},
	{Speed: 0},
	{Started: 0},
	{Auto: 0},
	{MoneyMultiplier: 0},
	{HoverUpgrade: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Layer: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	NewProject: class extends self.ISpriteInstance {},
	Afbeelding: class extends self.ISpriteInstance {},
	Muis: class extends self.IInstance {},
	Aanraking: class extends self.IInstance {},
	Tekst: class extends self.ITextInstance {},
	NewProject2: class extends self.ISpriteInstance {},
	Tekst2: class extends self.ITextInstance {},
	SpeedPrice: class extends self.ITextInstance {},
	MoneyPrice: class extends self.ITextInstance {},
	c2bcb432b9924503971fd73b5f32c313removebgpreview: class extends self.ISpriteInstance {},
	AutoPrice: class extends self.ITextInstance {},
	a0c1171745b8b57199db5fcea2f5removebgpreview: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	b599bd04938a2da758362c0ef74removebgpreview: class extends self.ISpriteInstance {},
	HTMLElement2: class extends self.IHTMLElementInstance {},
	Afbeelding2: class extends self.ISpriteInstance {},
	cursorpointersymbolpng: class extends self.ISpriteInstance {},
	Click2Start: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Particles2: class extends self.IParticlesInstance {},
	dollarsignpngtransparent: class extends self.ISpriteInstance {}
}